/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitasRouteImport } from './routes/visitas'
import { Route as VenderMeuImovelRouteImport } from './routes/vender-meu-imovel'
import { Route as ValorVenalRouteImport } from './routes/valor-venal'
import { Route as ValorMetroQuadradoRouteImport } from './routes/valor-metro-quadrado'
import { Route as UtilidadesRouteImport } from './routes/utilidades'
import { Route as TourVirtualRouteImport } from './routes/tour-virtual'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SejaCorretorRouteImport } from './routes/seja-corretor'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RepassesRouteImport } from './routes/repasses'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeiDoInquilinatoRouteImport } from './routes/lei-do-inquilinato'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as IndicesReajusteRouteImport } from './routes/indices-reajuste'
import { Route as IndicarImoveisRouteImport } from './routes/indicar-imoveis'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EscrituraDoImovelRouteImport } from './routes/escritura-do-imovel'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DadosEIndicesRouteImport } from './routes/dados-e-indices'
import { Route as CorretorParceiroRouteImport } from './routes/corretor-parceiro'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ContratoDeAluguelRouteImport } from './routes/contrato-de-aluguel'
import { Route as CondominiosRouteImport } from './routes/condominios'
import { Route as CentralDeAjudaRouteImport } from './routes/central-de-ajuda'
import { Route as CalculadoraVendaRouteImport } from './routes/calculadora-venda'
import { Route as CalculadoraIgpmRouteImport } from './routes/calculadora-igpm'
import { Route as CalculadoraAluguelRouteImport } from './routes/calculadora-aluguel'
import { Route as CadastroImovelRouteImport } from './routes/cadastro-imovel'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AreaProprietarioRouteImport } from './routes/area-proprietario'
import { Route as AreaMeuimovelRouteImport } from './routes/area-meuimovel'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as AlugarMeuImovelRouteImport } from './routes/alugar-meu-imovel'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostaSlugRouteImport } from './routes/proposta.$slug'
import { Route as ImovelSlugRouteImport } from './routes/imovel.$slug'

const VisitasRoute = VisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderMeuImovelRoute = VenderMeuImovelRouteImport.update({
  id: '/vender-meu-imovel',
  path: '/vender-meu-imovel',
  getParentRoute: () => rootRouteImport,
} as any)
const ValorVenalRoute = ValorVenalRouteImport.update({
  id: '/valor-venal',
  path: '/valor-venal',
  getParentRoute: () => rootRouteImport,
} as any)
const ValorMetroQuadradoRoute = ValorMetroQuadradoRouteImport.update({
  id: '/valor-metro-quadrado',
  path: '/valor-metro-quadrado',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilidadesRoute = UtilidadesRouteImport.update({
  id: '/utilidades',
  path: '/utilidades',
  getParentRoute: () => rootRouteImport,
} as any)
const TourVirtualRoute = TourVirtualRouteImport.update({
  id: '/tour-virtual',
  path: '/tour-virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaCorretorRoute = SejaCorretorRouteImport.update({
  id: '/seja-corretor',
  path: '/seja-corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RepassesRoute = RepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeiDoInquilinatoRoute = LeiDoInquilinatoRouteImport.update({
  id: '/lei-do-inquilinato',
  path: '/lei-do-inquilinato',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesReajusteRoute = IndicesReajusteRouteImport.update({
  id: '/indices-reajuste',
  path: '/indices-reajuste',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicarImoveisRoute = IndicarImoveisRouteImport.update({
  id: '/indicar-imoveis',
  path: '/indicar-imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrituraDoImovelRoute = EscrituraDoImovelRouteImport.update({
  id: '/escritura-do-imovel',
  path: '/escritura-do-imovel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosEIndicesRoute = DadosEIndicesRouteImport.update({
  id: '/dados-e-indices',
  path: '/dados-e-indices',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorParceiroRoute = CorretorParceiroRouteImport.update({
  id: '/corretor-parceiro',
  path: '/corretor-parceiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoDeAluguelRoute = ContratoDeAluguelRouteImport.update({
  id: '/contrato-de-aluguel',
  path: '/contrato-de-aluguel',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosRoute = CondominiosRouteImport.update({
  id: '/condominios',
  path: '/condominios',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDeAjudaRoute = CentralDeAjudaRouteImport.update({
  id: '/central-de-ajuda',
  path: '/central-de-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraVendaRoute = CalculadoraVendaRouteImport.update({
  id: '/calculadora-venda',
  path: '/calculadora-venda',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraIgpmRoute = CalculadoraIgpmRouteImport.update({
  id: '/calculadora-igpm',
  path: '/calculadora-igpm',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraAluguelRoute = CalculadoraAluguelRouteImport.update({
  id: '/calculadora-aluguel',
  path: '/calculadora-aluguel',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroImovelRoute = CadastroImovelRouteImport.update({
  id: '/cadastro-imovel',
  path: '/cadastro-imovel',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaProprietarioRoute = AreaProprietarioRouteImport.update({
  id: '/area-proprietario',
  path: '/area-proprietario',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaMeuimovelRoute = AreaMeuimovelRouteImport.update({
  id: '/area-meuimovel',
  path: '/area-meuimovel',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const AlugarMeuImovelRoute = AlugarMeuImovelRouteImport.update({
  id: '/alugar-meu-imovel',
  path: '/alugar-meu-imovel',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaSlugRoute = PropostaSlugRouteImport.update({
  id: '/proposta/$slug',
  path: '/proposta/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelSlugRoute = ImovelSlugRouteImport.update({
  id: '/imovel/$slug',
  path: '/imovel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/alugar-meu-imovel': typeof AlugarMeuImovelRoute
  '/anunciar': typeof AnunciarRoute
  '/area-meuimovel': typeof AreaMeuimovelRoute
  '/area-proprietario': typeof AreaProprietarioRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-imovel': typeof CadastroImovelRoute
  '/calculadora-aluguel': typeof CalculadoraAluguelRoute
  '/calculadora-igpm': typeof CalculadoraIgpmRoute
  '/calculadora-venda': typeof CalculadoraVendaRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/condominios': typeof CondominiosRoute
  '/contrato-de-aluguel': typeof ContratoDeAluguelRoute
  '/contratos': typeof ContratosRoute
  '/corretor-parceiro': typeof CorretorParceiroRoute
  '/dados-e-indices': typeof DadosEIndicesRoute
  '/dashboard': typeof DashboardRoute
  '/escritura-do-imovel': typeof EscrituraDoImovelRoute
  '/favoritos': typeof FavoritosRoute
  '/guias': typeof GuiasRoute
  '/indicar-imoveis': typeof IndicarImoveisRoute
  '/indices-reajuste': typeof IndicesReajusteRoute
  '/inteligencia': typeof InteligenciaRoute
  '/lancamentos': typeof LancamentosRoute
  '/lei-do-inquilinato': typeof LeiDoInquilinatoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/propostas': typeof PropostasRoute
  '/repasses': typeof RepassesRoute
  '/search': typeof SearchRoute
  '/seguranca': typeof SegurancaRoute
  '/seja-corretor': typeof SejaCorretorRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tour-virtual': typeof TourVirtualRoute
  '/utilidades': typeof UtilidadesRoute
  '/valor-metro-quadrado': typeof ValorMetroQuadradoRoute
  '/valor-venal': typeof ValorVenalRoute
  '/vender-meu-imovel': typeof VenderMeuImovelRoute
  '/visitas': typeof VisitasRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/proposta/$slug': typeof PropostaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/alugar-meu-imovel': typeof AlugarMeuImovelRoute
  '/anunciar': typeof AnunciarRoute
  '/area-meuimovel': typeof AreaMeuimovelRoute
  '/area-proprietario': typeof AreaProprietarioRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-imovel': typeof CadastroImovelRoute
  '/calculadora-aluguel': typeof CalculadoraAluguelRoute
  '/calculadora-igpm': typeof CalculadoraIgpmRoute
  '/calculadora-venda': typeof CalculadoraVendaRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/condominios': typeof CondominiosRoute
  '/contrato-de-aluguel': typeof ContratoDeAluguelRoute
  '/contratos': typeof ContratosRoute
  '/corretor-parceiro': typeof CorretorParceiroRoute
  '/dados-e-indices': typeof DadosEIndicesRoute
  '/dashboard': typeof DashboardRoute
  '/escritura-do-imovel': typeof EscrituraDoImovelRoute
  '/favoritos': typeof FavoritosRoute
  '/guias': typeof GuiasRoute
  '/indicar-imoveis': typeof IndicarImoveisRoute
  '/indices-reajuste': typeof IndicesReajusteRoute
  '/inteligencia': typeof InteligenciaRoute
  '/lancamentos': typeof LancamentosRoute
  '/lei-do-inquilinato': typeof LeiDoInquilinatoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/propostas': typeof PropostasRoute
  '/repasses': typeof RepassesRoute
  '/search': typeof SearchRoute
  '/seguranca': typeof SegurancaRoute
  '/seja-corretor': typeof SejaCorretorRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tour-virtual': typeof TourVirtualRoute
  '/utilidades': typeof UtilidadesRoute
  '/valor-metro-quadrado': typeof ValorMetroQuadradoRoute
  '/valor-venal': typeof ValorVenalRoute
  '/vender-meu-imovel': typeof VenderMeuImovelRoute
  '/visitas': typeof VisitasRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/proposta/$slug': typeof PropostaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/alugar-meu-imovel': typeof AlugarMeuImovelRoute
  '/anunciar': typeof AnunciarRoute
  '/area-meuimovel': typeof AreaMeuimovelRoute
  '/area-proprietario': typeof AreaProprietarioRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-imovel': typeof CadastroImovelRoute
  '/calculadora-aluguel': typeof CalculadoraAluguelRoute
  '/calculadora-igpm': typeof CalculadoraIgpmRoute
  '/calculadora-venda': typeof CalculadoraVendaRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/condominios': typeof CondominiosRoute
  '/contrato-de-aluguel': typeof ContratoDeAluguelRoute
  '/contratos': typeof ContratosRoute
  '/corretor-parceiro': typeof CorretorParceiroRoute
  '/dados-e-indices': typeof DadosEIndicesRoute
  '/dashboard': typeof DashboardRoute
  '/escritura-do-imovel': typeof EscrituraDoImovelRoute
  '/favoritos': typeof FavoritosRoute
  '/guias': typeof GuiasRoute
  '/indicar-imoveis': typeof IndicarImoveisRoute
  '/indices-reajuste': typeof IndicesReajusteRoute
  '/inteligencia': typeof InteligenciaRoute
  '/lancamentos': typeof LancamentosRoute
  '/lei-do-inquilinato': typeof LeiDoInquilinatoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/propostas': typeof PropostasRoute
  '/repasses': typeof RepassesRoute
  '/search': typeof SearchRoute
  '/seguranca': typeof SegurancaRoute
  '/seja-corretor': typeof SejaCorretorRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/tour-virtual': typeof TourVirtualRoute
  '/utilidades': typeof UtilidadesRoute
  '/valor-metro-quadrado': typeof ValorMetroQuadradoRoute
  '/valor-venal': typeof ValorVenalRoute
  '/vender-meu-imovel': typeof VenderMeuImovelRoute
  '/visitas': typeof VisitasRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/proposta/$slug': typeof PropostaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/alugar-meu-imovel'
    | '/anunciar'
    | '/area-meuimovel'
    | '/area-proprietario'
    | '/cadastro'
    | '/cadastro-imovel'
    | '/calculadora-aluguel'
    | '/calculadora-igpm'
    | '/calculadora-venda'
    | '/central-de-ajuda'
    | '/condominios'
    | '/contrato-de-aluguel'
    | '/contratos'
    | '/corretor-parceiro'
    | '/dados-e-indices'
    | '/dashboard'
    | '/escritura-do-imovel'
    | '/favoritos'
    | '/guias'
    | '/indicar-imoveis'
    | '/indices-reajuste'
    | '/inteligencia'
    | '/lancamentos'
    | '/lei-do-inquilinato'
    | '/login'
    | '/privacidade'
    | '/propostas'
    | '/repasses'
    | '/search'
    | '/seguranca'
    | '/seja-corretor'
    | '/sobre'
    | '/termos'
    | '/tour-virtual'
    | '/utilidades'
    | '/valor-metro-quadrado'
    | '/valor-venal'
    | '/vender-meu-imovel'
    | '/visitas'
    | '/imovel/$slug'
    | '/proposta/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/alugar-meu-imovel'
    | '/anunciar'
    | '/area-meuimovel'
    | '/area-proprietario'
    | '/cadastro'
    | '/cadastro-imovel'
    | '/calculadora-aluguel'
    | '/calculadora-igpm'
    | '/calculadora-venda'
    | '/central-de-ajuda'
    | '/condominios'
    | '/contrato-de-aluguel'
    | '/contratos'
    | '/corretor-parceiro'
    | '/dados-e-indices'
    | '/dashboard'
    | '/escritura-do-imovel'
    | '/favoritos'
    | '/guias'
    | '/indicar-imoveis'
    | '/indices-reajuste'
    | '/inteligencia'
    | '/lancamentos'
    | '/lei-do-inquilinato'
    | '/login'
    | '/privacidade'
    | '/propostas'
    | '/repasses'
    | '/search'
    | '/seguranca'
    | '/seja-corretor'
    | '/sobre'
    | '/termos'
    | '/tour-virtual'
    | '/utilidades'
    | '/valor-metro-quadrado'
    | '/valor-venal'
    | '/vender-meu-imovel'
    | '/visitas'
    | '/imovel/$slug'
    | '/proposta/$slug'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/alugar-meu-imovel'
    | '/anunciar'
    | '/area-meuimovel'
    | '/area-proprietario'
    | '/cadastro'
    | '/cadastro-imovel'
    | '/calculadora-aluguel'
    | '/calculadora-igpm'
    | '/calculadora-venda'
    | '/central-de-ajuda'
    | '/condominios'
    | '/contrato-de-aluguel'
    | '/contratos'
    | '/corretor-parceiro'
    | '/dados-e-indices'
    | '/dashboard'
    | '/escritura-do-imovel'
    | '/favoritos'
    | '/guias'
    | '/indicar-imoveis'
    | '/indices-reajuste'
    | '/inteligencia'
    | '/lancamentos'
    | '/lei-do-inquilinato'
    | '/login'
    | '/privacidade'
    | '/propostas'
    | '/repasses'
    | '/search'
    | '/seguranca'
    | '/seja-corretor'
    | '/sobre'
    | '/termos'
    | '/tour-virtual'
    | '/utilidades'
    | '/valor-metro-quadrado'
    | '/valor-venal'
    | '/vender-meu-imovel'
    | '/visitas'
    | '/imovel/$slug'
    | '/proposta/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AlugarMeuImovelRoute: typeof AlugarMeuImovelRoute
  AnunciarRoute: typeof AnunciarRoute
  AreaMeuimovelRoute: typeof AreaMeuimovelRoute
  AreaProprietarioRoute: typeof AreaProprietarioRoute
  CadastroRoute: typeof CadastroRoute
  CadastroImovelRoute: typeof CadastroImovelRoute
  CalculadoraAluguelRoute: typeof CalculadoraAluguelRoute
  CalculadoraIgpmRoute: typeof CalculadoraIgpmRoute
  CalculadoraVendaRoute: typeof CalculadoraVendaRoute
  CentralDeAjudaRoute: typeof CentralDeAjudaRoute
  CondominiosRoute: typeof CondominiosRoute
  ContratoDeAluguelRoute: typeof ContratoDeAluguelRoute
  ContratosRoute: typeof ContratosRoute
  CorretorParceiroRoute: typeof CorretorParceiroRoute
  DadosEIndicesRoute: typeof DadosEIndicesRoute
  DashboardRoute: typeof DashboardRoute
  EscrituraDoImovelRoute: typeof EscrituraDoImovelRoute
  FavoritosRoute: typeof FavoritosRoute
  GuiasRoute: typeof GuiasRoute
  IndicarImoveisRoute: typeof IndicarImoveisRoute
  IndicesReajusteRoute: typeof IndicesReajusteRoute
  InteligenciaRoute: typeof InteligenciaRoute
  LancamentosRoute: typeof LancamentosRoute
  LeiDoInquilinatoRoute: typeof LeiDoInquilinatoRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PropostasRoute: typeof PropostasRoute
  RepassesRoute: typeof RepassesRoute
  SearchRoute: typeof SearchRoute
  SegurancaRoute: typeof SegurancaRoute
  SejaCorretorRoute: typeof SejaCorretorRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  TourVirtualRoute: typeof TourVirtualRoute
  UtilidadesRoute: typeof UtilidadesRoute
  ValorMetroQuadradoRoute: typeof ValorMetroQuadradoRoute
  ValorVenalRoute: typeof ValorVenalRoute
  VenderMeuImovelRoute: typeof VenderMeuImovelRoute
  VisitasRoute: typeof VisitasRoute
  ImovelSlugRoute: typeof ImovelSlugRoute
  PropostaSlugRoute: typeof PropostaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitas': {
      id: '/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof VisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender-meu-imovel': {
      id: '/vender-meu-imovel'
      path: '/vender-meu-imovel'
      fullPath: '/vender-meu-imovel'
      preLoaderRoute: typeof VenderMeuImovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valor-venal': {
      id: '/valor-venal'
      path: '/valor-venal'
      fullPath: '/valor-venal'
      preLoaderRoute: typeof ValorVenalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valor-metro-quadrado': {
      id: '/valor-metro-quadrado'
      path: '/valor-metro-quadrado'
      fullPath: '/valor-metro-quadrado'
      preLoaderRoute: typeof ValorMetroQuadradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilidades': {
      id: '/utilidades'
      path: '/utilidades'
      fullPath: '/utilidades'
      preLoaderRoute: typeof UtilidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-virtual': {
      id: '/tour-virtual'
      path: '/tour-virtual'
      fullPath: '/tour-virtual'
      preLoaderRoute: typeof TourVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-corretor': {
      id: '/seja-corretor'
      path: '/seja-corretor'
      fullPath: '/seja-corretor'
      preLoaderRoute: typeof SejaCorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repasses': {
      id: '/repasses'
      path: '/repasses'
      fullPath: '/repasses'
      preLoaderRoute: typeof RepassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lei-do-inquilinato': {
      id: '/lei-do-inquilinato'
      path: '/lei-do-inquilinato'
      fullPath: '/lei-do-inquilinato'
      preLoaderRoute: typeof LeiDoInquilinatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices-reajuste': {
      id: '/indices-reajuste'
      path: '/indices-reajuste'
      fullPath: '/indices-reajuste'
      preLoaderRoute: typeof IndicesReajusteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicar-imoveis': {
      id: '/indicar-imoveis'
      path: '/indicar-imoveis'
      fullPath: '/indicar-imoveis'
      preLoaderRoute: typeof IndicarImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritura-do-imovel': {
      id: '/escritura-do-imovel'
      path: '/escritura-do-imovel'
      fullPath: '/escritura-do-imovel'
      preLoaderRoute: typeof EscrituraDoImovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-e-indices': {
      id: '/dados-e-indices'
      path: '/dados-e-indices'
      fullPath: '/dados-e-indices'
      preLoaderRoute: typeof DadosEIndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor-parceiro': {
      id: '/corretor-parceiro'
      path: '/corretor-parceiro'
      fullPath: '/corretor-parceiro'
      preLoaderRoute: typeof CorretorParceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato-de-aluguel': {
      id: '/contrato-de-aluguel'
      path: '/contrato-de-aluguel'
      fullPath: '/contrato-de-aluguel'
      preLoaderRoute: typeof ContratoDeAluguelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios': {
      id: '/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof CondominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-de-ajuda': {
      id: '/central-de-ajuda'
      path: '/central-de-ajuda'
      fullPath: '/central-de-ajuda'
      preLoaderRoute: typeof CentralDeAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-venda': {
      id: '/calculadora-venda'
      path: '/calculadora-venda'
      fullPath: '/calculadora-venda'
      preLoaderRoute: typeof CalculadoraVendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-igpm': {
      id: '/calculadora-igpm'
      path: '/calculadora-igpm'
      fullPath: '/calculadora-igpm'
      preLoaderRoute: typeof CalculadoraIgpmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-aluguel': {
      id: '/calculadora-aluguel'
      path: '/calculadora-aluguel'
      fullPath: '/calculadora-aluguel'
      preLoaderRoute: typeof CalculadoraAluguelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-imovel': {
      id: '/cadastro-imovel'
      path: '/cadastro-imovel'
      fullPath: '/cadastro-imovel'
      preLoaderRoute: typeof CadastroImovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-proprietario': {
      id: '/area-proprietario'
      path: '/area-proprietario'
      fullPath: '/area-proprietario'
      preLoaderRoute: typeof AreaProprietarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-meuimovel': {
      id: '/area-meuimovel'
      path: '/area-meuimovel'
      fullPath: '/area-meuimovel'
      preLoaderRoute: typeof AreaMeuimovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alugar-meu-imovel': {
      id: '/alugar-meu-imovel'
      path: '/alugar-meu-imovel'
      fullPath: '/alugar-meu-imovel'
      preLoaderRoute: typeof AlugarMeuImovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta/$slug': {
      id: '/proposta/$slug'
      path: '/proposta/$slug'
      fullPath: '/proposta/$slug'
      preLoaderRoute: typeof PropostaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$slug': {
      id: '/imovel/$slug'
      path: '/imovel/$slug'
      fullPath: '/imovel/$slug'
      preLoaderRoute: typeof ImovelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AlugarMeuImovelRoute: AlugarMeuImovelRoute,
  AnunciarRoute: AnunciarRoute,
  AreaMeuimovelRoute: AreaMeuimovelRoute,
  AreaProprietarioRoute: AreaProprietarioRoute,
  CadastroRoute: CadastroRoute,
  CadastroImovelRoute: CadastroImovelRoute,
  CalculadoraAluguelRoute: CalculadoraAluguelRoute,
  CalculadoraIgpmRoute: CalculadoraIgpmRoute,
  CalculadoraVendaRoute: CalculadoraVendaRoute,
  CentralDeAjudaRoute: CentralDeAjudaRoute,
  CondominiosRoute: CondominiosRoute,
  ContratoDeAluguelRoute: ContratoDeAluguelRoute,
  ContratosRoute: ContratosRoute,
  CorretorParceiroRoute: CorretorParceiroRoute,
  DadosEIndicesRoute: DadosEIndicesRoute,
  DashboardRoute: DashboardRoute,
  EscrituraDoImovelRoute: EscrituraDoImovelRoute,
  FavoritosRoute: FavoritosRoute,
  GuiasRoute: GuiasRoute,
  IndicarImoveisRoute: IndicarImoveisRoute,
  IndicesReajusteRoute: IndicesReajusteRoute,
  InteligenciaRoute: InteligenciaRoute,
  LancamentosRoute: LancamentosRoute,
  LeiDoInquilinatoRoute: LeiDoInquilinatoRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PropostasRoute: PropostasRoute,
  RepassesRoute: RepassesRoute,
  SearchRoute: SearchRoute,
  SegurancaRoute: SegurancaRoute,
  SejaCorretorRoute: SejaCorretorRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  TourVirtualRoute: TourVirtualRoute,
  UtilidadesRoute: UtilidadesRoute,
  ValorMetroQuadradoRoute: ValorMetroQuadradoRoute,
  ValorVenalRoute: ValorVenalRoute,
  VenderMeuImovelRoute: VenderMeuImovelRoute,
  VisitasRoute: VisitasRoute,
  ImovelSlugRoute: ImovelSlugRoute,
  PropostaSlugRoute: PropostaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
